[book]
language = "en"
src = "."
title = "pokemon-lucid"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/pkLucid/Pokemon-Lucid"
edit-url-template = "https://github.com/pkLucid/Pokemon-Lucid/edit/master/lucid_book/{path}"
site-url = "/pokemon-lucid/"
no-section-label = true
sidebar-header-nav = false

[preprocessor.fix_links]
command = "python3 fix_links.py"
